name: deploy html
on:
  push:
    branches:
    - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Deploy static site to S3 bucket-serg
      run: aws s3 sync ./ s3://service-business-bt-com-serg-dcp.digital-ent-int.bt.com --delete
